k8s-monitoring:
  cluster:
    name: Nomster Cluster
  externalServices:
    prometheus:
      secret:
        create: false
        name: "prometheus-credentials"
        namespace: "grafana"
    loki:
      secret:
        create: false
        name: "loki-credentials"
        namespace: "grafana"
    tempo:
      secret:
        create: false
        name: "tempo-credentials"
        namespace: "grafana"
  metrics:
    enabled: true
    alloy:
      metricsTuning:
        useIntegrationAllowList: true
    cost:
      enabled: false
    kepler:
      enabled: false
    node-exporter:
      enabled: true
  logs:
    enabled: true
    pod_logs:
      enabled: true
    cluster_events:
      enabled: true
  traces:
    enabled: true
  receivers:
    grpc:
      enabled: true
    http:
      enabled: true
    zipkin:
      enabled: true
    grafanaCloudMetrics:
      enabled: false
  opencost:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-operator-crds:
    enabled: true
  kepler:
    enabled: true
  alloy: {}
  alloy-events: {}
  alloy-logs: {}