k8s-monitoring:
  cluster:
    name: Nomster Cluster
  externalServices:
    prometheus:
      host: <path:k8s/data/grafana#url_prometheus>
      basicAuth:
        username: <path:k8s/data/grafana#user_prometheus>
        password: <path:k8s/data/grafana#token>
    loki:
      host: <path:k8s/data/grafana#url_loki>
      basicAuth:
        username: <path:k8s/data/grafana#user_loki>
        password: <path:k8s/data/grafana#token>
    tempo:
      host: <path:k8s/data/grafana#url_tempo>
      basicAuth:
        username: <path:k8s/data/grafana#user_tempo>
        password: <path:k8s/data/grafana#token>
  metrics:
    enabled: true
    alloy:
      metricsTuning:
        useIntegrationAllowList: true
    cost:
      enabled: false
    kepler:
      enabled: false
    node-exporter:
      enabled: true
  logs:
    enabled: true
    pod_logs:
      enabled: true
    cluster_events:
      enabled: true
  traces:
    enabled: true
  receivers:
    grpc:
      enabled: true
    http:
      enabled: true
    zipkin:
      enabled: true
    grafanaCloudMetrics:
      enabled: false
  opencost:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-operator-crds:
    enabled: true
  kepler:
    enabled: true
  alloy: {}
  alloy-events: {}
  alloy-logs: {}